# Generated by Django 4.2.19 on 2025-04-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('ciudad_nacimiento', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad_residencia', models.CharField(blank=True, max_length=255, null=True)),
                ('afiliada', models.BooleanField(default=False)),
                ('diagnostico_confirmado', models.BooleanField(default=False)),
            ],
        ),
    ]
